"""The shipped wiki demo: generated by the real generator, self-contained,
deterministic, and sealed so the artifact itself can be re-verified. The
negative fixture: a tampered page in the demo pack must turn DRIFT."""
import importlib.util
import re
import tempfile
import xml.dom.minidom as minidom
from pathlib import Path

from index_graph.wiki.seal import extract_embedded_pack, verify_wiki

_spec = importlib.util.spec_from_file_location(
    "wiki_demo", Path(__file__).resolve().parents[1] / "examples" / "wiki_demo.py")
demo = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(demo)


def test_demo_renders_self_contained_verified_wiki():
    with tempfile.TemporaryDirectory() as tmp:
        repo = demo.build_repo(Path(tmp))
        html = demo.render(repo)
        report = verify_wiki(extract_embedded_pack(html), repo)
        assert report["verdict"] == "MATCH"
    assert html.lstrip().lower().startswith("<!doctype html>")
    assert "<link" not in html.lower() and "@import" not in html
    svg = re.search(r"<svg.*?</svg>", html, re.S)
    assert svg is not None
    minidom.parseString(svg.group(0))


def test_demo_is_path_independent_deterministic():
    with tempfile.TemporaryDirectory() as a, tempfile.TemporaryDirectory() as b:
        ha = demo.render(demo.build_repo(Path(a)))
        hb = demo.render(demo.build_repo(Path(b)))
    assert ha == hb


def test_demo_pack_rejects_a_tampered_page():
    with tempfile.TemporaryDirectory() as tmp:
        repo = demo.build_repo(Path(tmp))
        pack = extract_embedded_pack(demo.render(repo))
        pack["pages"][0]["module_count"] = 999
        report = verify_wiki(pack, repo)
    assert report["verdict"] == "DRIFT"
    assert any(f["rule"] == "page-tampered" for f in report["findings"])


def test_committed_demo_artifact_is_the_sealed_wiki():
    committed = Path(__file__).resolve().parents[1] / "examples" / "wiki-demo.html"
    pack = extract_embedded_pack(committed.read_text(encoding="utf-8"))
    assert pack["schema"] == "index.wiki/1"
    assert pack["repo"] == demo.REPO_NAME
    assert pack["commit"] == "unversioned"  # synthetic fixture, not a git repo
